### ISSUE TITLE
Add pet status controller API endpoint

### ISSUE THREAD

**Issue by Chris-Johnston** [Chris-Johnston/PGTRTKD3000DGOTY#50]
Add an API controller that gets the status of a pet based on the activity.

This will be used to populate the pet details page.

Should go under the endpoint
`api/Pet/{petid}/Status`

**Comment by anishprasad01** [comment]
status api should have:

user status: 3 pet statuses

pet status: 1 pet statuses

time of when actions can be performed again

all attributes of pet and determined attributes

**Comment by anishprasad01** [comment]
Fixed by #57
